# This is a basic workflow to help you get started with Actions

name: Version Update

# Controls when the action will run. 
on:
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  version-check:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: setup node
        run: npm install

      - name: Check if version has been updated
        id: check
        uses: EndBug/version-check@v1
        with:
          diff-search: true
          file-url: https://raw.githubusercontent.com/lharri73/DBC-Language-Syntax/master/package.json
          static-checking: localIsNew
      
      - name: Verify Version
        if: steps.check.outputs.changed == 'false'
        run: 'echo "Version not incremented!" ; exit 1'
      
      - name: Changelog update
        run: if [ "`git diff ..master changelog.md`" = "" ] ; then exit 1; else exit 0; fi;
          

